### ISSUE TITLE
Langevin gradient step size in code vs in paper

### ISSUE THREAD

**Issue by marekjg** [openai/ebm_code_release#2]
In the paper the langevin dynamics scales the gradient as 0.5 * &lambda; + w sampled from normal distribution with 0 mean and &lambda; standard deviation. However, in the code (e.x. imagenet_demo.py), gradient is multiplied by step_lr which is 180 by default and the noise is generated with 0.005 standard deviation. Am I missing something or the paper shows equation that is justified by theory but in practice it is better to scale energy gradient different than noise?

**Comment by yilundu** [comment]
Sorry about the confusion. We unintentionally used the same variable λ for both terms. The λ parameterizing the standard deviation is different than the one for the gradient.

**Comment by GloryyrolG** [comment]
So it is like using some temperatures to sharpen EBMs and `T` is included in `step size`?
