### ISSUE TITLE
AUROC computation

### ISSUE THREAD

**Issue by a7b23** [openai/ebm_code_release#6]
In section 4.4 "Out-of-Distribution Generalization" how do you compute the AUROC scores from the EBM model? The score function is un-normalized, as opposed to the likelihood which is between 0 and 1. So how is the AUROC score computed then?

**Comment by yilundu** [comment]
To compute AUROC, you just need to compare the relative likelihood of real and out-of-distribution samples, which you can obtain from the energy function.

**Comment by yilundu** [comment]
The energyevalmix function in ebm_sandbox.py shows how to compute the AUROC.

Specifically, you label real data points as 1 and fake data points as 0, and use the negative energy function as the score threshold (which does not have to be between 0 and 1)

**Comment by a7b23** [comment]
Great, thanks a lot!
